# Generated by Django 4.2.1 on 2023-07-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='products',
            field=models.CharField(max_length=255),
        ),
    ]
