# Generated by Django 4.2.1 on 2023-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0002_alter_order_products_alter_order_list_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p_barcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_list',
            name='p_barcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
